SENTIMENT_OPTIONS = 9
SENTIMENT_INITIAL = 5

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (100, 150, 255)
RED = (255, 0, 0)

import pygame.freetype
pygame.freetype.init()

SMALL_FONT_SIZE = 15
SMALL_FONT = pygame.freetype.SysFont("arial", SMALL_FONT_SIZE)

LARGE_FONT_SIZE = 20
LARGE_FONT = pygame.freetype.SysFont("arial", LARGE_FONT_SIZE)

SAMPLE_RATE = 44100

HEIGHT = 560
WIDTH = 720

BUTTON_SIZE = 100
SCALE_WIDTH = 5
TAB_WIDTH = 5*SCALE_WIDTH
SCALE_HEIGHT = 3*HEIGHT//4
NEXT_WIDTH = 100
NEXT_HEIGHT = 40

SCALE_NUMBER_OFFSET = 20
SCALE_LABEL_OFFSET = 50

SCALE_CENTER = 3*WIDTH//4 - 20
BUTTON_A_X = WIDTH//4 - BUTTON_SIZE//2
BUTTON_A_Y = HEIGHT//2 - BUTTON_SIZE//2
BUTTON_B_X = 2*WIDTH//4 - BUTTON_SIZE//2
BUTTON_B_Y = HEIGHT//2 - BUTTON_SIZE//2
SCALE_X = SCALE_CENTER - SCALE_WIDTH//2
SCALE_Y = HEIGHT//2 - SCALE_HEIGHT//2

BUTTON_A2_X = WIDTH//4 - BUTTON_SIZE//2
BUTTON_A2_Y = HEIGHT//2 - BUTTON_SIZE//2
BUTTON_B2_X = 3*WIDTH//4 - BUTTON_SIZE//2
BUTTON_B2_Y = HEIGHT//2 - BUTTON_SIZE//2

NEXT_CENTER2_X = 3*WIDTH//4
NEXT_CENTER2_Y = HEIGHT//4
NEXT_BOX2_X = NEXT_CENTER2_X - NEXT_WIDTH//2
NEXT_BOX2_Y = NEXT_CENTER2_Y - NEXT_HEIGHT//2
NEXT_TEXT2_X = NEXT_CENTER2_X - LARGE_FONT_SIZE
NEXT_TEXT2_Y = NEXT_CENTER2_Y - LARGE_FONT_SIZE//2

SCALE_WIDTH2 = 1*WIDTH//2
SCALE_HEIGHT2 = 5
SCALE_CENTER2 = 3*HEIGHT//4
SCALE_X2 = WIDTH//2 - SCALE_WIDTH2//2
SCALE_Y2 = SCALE_CENTER2 - SCALE_HEIGHT2//2
SCALE_NUMBER_Y2 = SCALE_CENTER2 + SCALE_NUMBER_OFFSET
SCALE_LABEL_Y2 = SCALE_CENTER2 + SCALE_LABEL_OFFSET
SCALE_LABEL_X2_1 = WIDTH//2 - SCALE_WIDTH2//2 - SMALL_FONT_SIZE*2
SCALE_LABEL_X2_2 = WIDTH//2 + SCALE_WIDTH2//2 - SMALL_FONT_SIZE*2

TAB_Y2 = SCALE_CENTER2 - TAB_WIDTH//2

NEXT_CENTER_X = 3*WIDTH//8
NEXT_CENTER_Y = 3*HEIGHT//4
NEXT_BOX_X = NEXT_CENTER_X - NEXT_WIDTH//2
NEXT_BOX_Y = NEXT_CENTER_Y - NEXT_HEIGHT//2
NEXT_TEXT_X = NEXT_CENTER_X - LARGE_FONT_SIZE
NEXT_TEXT_Y = NEXT_CENTER_Y - LARGE_FONT_SIZE//2

TAB_HEIGHT = 5
TAB_X = SCALE_CENTER - TAB_WIDTH//2
SCALE_NUMBER_X = SCALE_CENTER + SCALE_NUMBER_OFFSET
SCALE_LABEL_X = SCALE_CENTER + SCALE_LABEL_OFFSET
SCALE_LABEL_Y_1 = HEIGHT//2 - SCALE_HEIGHT//2 - SMALL_FONT_SIZE//2
SCALE_LABEL_Y_2 = HEIGHT//2 + SCALE_HEIGHT//2 - SMALL_FONT_SIZE//2

EXPERIMENT_TEXT_X = NEXT_CENTER_X - SMALL_FONT_SIZE*15
EXPERIMENT_TEXT_Y1 = HEIGHT//4 - 2*SMALL_FONT_SIZE//2
EXPERIMENT_TEXT_Y2 = HEIGHT//4
EXPERIMENT_TEXT_Y3 = HEIGHT//4 + 2*SMALL_FONT_SIZE//2

SIMILARITY_INDICATOR_SIZE = 10