import pygame

SENTIMENT_OPTIONS = 9
SENTIMENT_INITIAL = 5

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

pygame.init()
pygame.font.init()
TEXT_SIZE = 10
SCALE_FONT = pygame.font.SysFont("arial", TEXT_SIZE)

PROMPTING_TEXT_SIZE = 15
PROMPTING_FONT = pygame.font.SysFont("arial", PROMPTING_TEXT_SIZE)

NEXT_TEXT_SIZE = 20
NEXT_FONT = pygame.font.SysFont("arial", NEXT_TEXT_SIZE)

HEIGHT = 560
WIDTH = 720

BUTTON_SIZE = 100
SCALE_WIDTH = 5
SCALE_HEIGHT = 3*HEIGHT//4
NEXT_WIDTH = 100
NEXT_HEIGHT = 40

SCALE_TEXT_OFFSET = 20
SCALE_QUESTION_OFFSET = 50

SCALE_CENTER = 3*WIDTH//4 - 20
BUTTON_A_X = WIDTH//4 - BUTTON_SIZE//2
BUTTON_A_Y = HEIGHT//2 - BUTTON_SIZE//2
BUTTON_B_X = 2*WIDTH//4 - BUTTON_SIZE//2
BUTTON_B_Y = HEIGHT//2 - BUTTON_SIZE//2
SCALE_X = SCALE_CENTER - SCALE_WIDTH//2
SCALE_Y = HEIGHT//2 - SCALE_HEIGHT//2

BUTTON_C_X = 3*WIDTH//8 - BUTTON_SIZE//2
BUTTON_C_Y = HEIGHT//2 - BUTTON_SIZE//2

PROMPTING_X = WIDTH//2
PROMPTING_Y1 = HEIGHT//2 - 4*PROMPTING_TEXT_SIZE//2
PROMPTING_Y2 = HEIGHT//2 - 2*PROMPTING_TEXT_SIZE//2
PROMPTING_Y3 = HEIGHT//2
PROMPTING_Y4 = HEIGHT//2 + 2*PROMPTING_TEXT_SIZE//2

NEXT_CENTER_X = 3*WIDTH//8
NEXT_CENTER_Y = 3*HEIGHT//4
NEXT_BOX_X = NEXT_CENTER_X - NEXT_WIDTH//2
NEXT_BOX_Y = NEXT_CENTER_Y - NEXT_HEIGHT//2
NEXT_TEXT_X = NEXT_CENTER_X - NEXT_TEXT_SIZE
NEXT_TEXT_Y = NEXT_CENTER_Y - NEXT_TEXT_SIZE//2

TAB_WIDTH = 5*SCALE_WIDTH
TAB_HEIGHT = 5
TAB_X = SCALE_CENTER - TAB_WIDTH//2
SCALE_TEXT_X = SCALE_CENTER + SCALE_TEXT_OFFSET
SCALE_QUESTION_X = SCALE_CENTER + SCALE_QUESTION_OFFSET
SCALE_QUESTION_Y_1 = HEIGHT//2 - 2*TEXT_SIZE//2
SCALE_QUESTION_Y_2 = HEIGHT//2

SIMILARITY_INDICATOR_SIZE = 10